version: '2.1'

services:
  server:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - .:/src
    working_dir: /src
    command: python3 worker.py
    links:
      - redis

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379

